sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: never

cache:
  directories:
    - $HOME/.composer/cache

# Test main supported versions of PHP against latest WP.
php:
  - 5.5
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0


before_script:
  - mysql -e 'DROP DATABASE IF EXISTS `wc_boltpay_test`;'
  - bash tests/bin/install.sh wc_boltpay_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit
  - bash tests/bin/check_reports.sh

after_script:
  - bash tests/bin/travis.sh after
